apiVersion: apps/v1
kind: Deployment
metadata:
  name: jung-app
  labels:
    app: jung-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-jung-app
  template:
    metadata:
      labels:
        app: jung-app
    spec:
      containers:
        - name: sitthaja-test-repo
          image: 516577126946.dkr.ecr.ap-southeast-1.amazonaws.com/sitthaja-test-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
