name: Node js app deploy to EKS
on:
  push:
    branches:
      - jung-app

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  actions: read # for GitHub action CodeQL
  security-events: write

jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.29.3'
        id: install
      
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build, tag, and push Docker image to AWS ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sitthaja-test-repo
          IMAGE_TAG: 1.1
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY

      - name: update Kube config
        run: aws eks update-kubeconfig --name sitthaja-test-cluster

      - name: deploy to EKS
        run : |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          