name: Terraform Apply

on:
  push:
    branches:
      - terraform-01

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Init
        run: terraform init

      - name: Import existing EC2 instance
        run: terraform import aws_instance.jung-ec2 i-08dfaf1d272e3fd58
        # Note: Replace <instance-id> with your actual instance ID.

      - name: Import existing Security Group
        run: terraform import aws_security_group.jung-sg sg-0bd9413fe8859fc30
        # Note: Replace <security-group-id> with your actual security group ID.


      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
