name: Terraform Apply

on:
  push:
    branches:
      - terraform-01

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Init
        run: terraform init

      - name: Import existing EC2 instance
        run: terraform import aws_instance.jung-ec2 <instance-id>
        # Note: Replace <instance-id> with your actual instance ID.

      - name: Import existing Security Group
        run: terraform import aws_security_group.jung-sg <security-group-id>
        # Note: Replace <security-group-id> with your actual security group ID.

      - name: Import existing VPC Endpoint for SSM
        run: terraform import aws_vpc_endpoint.ssm <vpc-endpoint-id-ssm>
        # Note: Replace <vpc-endpoint-id-ssm> with your actual VPC endpoint ID for SSM.

      - name: Import existing VPC Endpoint for EC2 Messages
        run: terraform import aws_vpc_endpoint.ec2messages <vpc-endpoint-id-ec2messages>
        # Note: Replace <vpc-endpoint-id-ec2messages> with your actual VPC endpoint ID for EC2 messages.

      - name: Import existing VPC Endpoint for SSM Messages
        run: terraform import aws_vpc_endpoint.ssmmessages <vpc-endpoint-id-ssmmessages>
        # Note: Replace <vpc-endpoint-id-ssmmessages> with your actual VPC endpoint ID for SSM messages.

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
